# General
ts = ['timestamp']
pos_coords  = ['x', 'y', 'z']
quat_coords = ['qx', 'qy', 'qz', 'qw']
velocity = ['velocity_x', 'velocity_y', 'velocity_z']
speed = ['speed']
dt = 0.005          # Sampling time [s]

# Kalman filter
dim_x = 14          # state vector dimension
dim_z = 7           # measurement vector dimension
var_R = 1e-6        # measurement noise variance
var_Q_pos = 1e3     # process noise variance (positional components)
var_Q_ang = 4e6     # process noise variance (angular components)

# RNN
dataset =
prepare_raw_dataset=False,
prepare_test=False,
add_sliding_window=False,
load_before_split_with_sliding=False,
load_test_val_train_split_with_sliding=True,
split_train_test_with_sliding=False,
load_train_test_with_sliding=False